### ISSUE TITLE
大佬。。可以发下数据库文件吗？我我邮箱491198685@qq.com谢谢！

### ISSUE THREAD

**Issue by herohalo** [ayang818/TrainBookingSystem#1]

**Comment by ayang818** [comment]
> _No description provided._

所有的数据库结构都是在```src/main/resources/db/migration```下的，你只要在pom.xml里面配置好自己的数据库信息，然后在文件根目录运行```mvn flyway:migrate```就可以自动构建所有的数据表，关于具体数据啥的可以自己造。我使用的是maven的flyway这一数据库版本管理plugin，更多的flyway的使用可以查看flyway的<a href="https://flywaydb.org/">官网</a>

**Comment by herohalo** [comment]
好的！谢谢大佬！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"杨丰畅"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 下午2:25
收件人:&nbsp;"ayang818/TrainBookingSystem"<TrainBookingSystem@noreply.github.com&gt;;
抄送:&nbsp;" hope"<491198685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ayang818/TrainBookingSystem] 大佬。。可以发下数据库文件吗？我我邮箱491198685@qq.com谢谢！ (#1)



 
No description provided.
  
所有的数据库结构都是在src/main/resources/db/migration下的，你只要在pom.xml里面配置好自己的数据库信息，然后在文件根目录运行mvn flyway:migrate就可以自动构建所有的数据表，关于具体数据啥的可以自己造。我使用的是maven的flyway这一数据库版本管理plugin，更多的flyway的使用可以查看flyway的官网
